#
# Deploy the logging component to OpenShift.
#
# Additionally the system:openshift:scc:privileged ClusterRoleBinding for
# the fluentd pod ServiceAccount needs to be created manually.
#
---
global:
  splunk:
    hec:
      host: inputs.prd-p-4ojra.splunkcloud.com # Set Splunk IP address
      port: 8088 # Set Splunk HEC port
      protocol: https
      token: a57f124f-a5c7-4a86-a482-11d533283f6f # Hec token created
      insecureSSL: true
      indexName: rates_prj_index # default index if others not set
  kubernetes:
    clusterName: "crc.testing"

splunk-kubernetes-logging:
  enabled: true
  kubernetes:
    # the next actually sets .securityContext.privileged
    # privileged is required, due to SELinux preventing
    # write access for the *.pos files of fluentd.
    securityContext: true
  #fluentd:
  #  path: /var/log/containers/*rates*.log
  containers:
    logFormatType: cri
    logFormat: "%Y-%m-%dT%H:%M:%S.%N%:z"
  journalLogPath: /var/log/journal
  logs:
    ratesinfoprj:
      from:
        file:
          path: /var/log/containers/*rates*.log
#    # The `kube-audit` file has another path on OpenShift
#    kube-audit:
#      from:
#        file:
#          path: /var/log/kube-apiserver/audit.log
#    # Next 2 logfiles are specific to OpenShift
#    openshift-audit:
#      from:
#        file:
#          path: /var/log/openshift-apiserver/audit.log
#      timestampExtraction:
#        format: "%Y-%m-%dT%H:%M:%SZ"
#      sourcetype: kube:openshift-apiserver-audit
#    oauth-audit:
#      from:
#        file:
#          path: /var/log/oauth-apiserver/audit.log
#      timestampExtraction:
#        format: "%Y-%m-%dT%H:%M:%SZ"
#      sourcetype: kube:oauth-apiserver-audit

splunk-kubernetes-metrics:
  enabled: false

splunk-kubernetes-objects:
  enabled: false

